title = "Debug cfg file for Telemetr db"

[databases]
database = "telemetr"
user = "telemetr"
password = "qgpTz93xkPgA3csg"
host = "localhost"
port = "5432"

[secret_key]
secret_key = "3YxJMT5ykqJIzNSPfFPP"

[client]
api_id = 1420226
api_hash = 'b5e4e95f233a379ed2a92381b939fbb7'